task 4
htmlacademy-htmlcss/1996945-sedona-34 pull request #4
Opened 2022-06-25 19:15 UTC by RenEstel

2022-06-26 03:11 UTC, Dima-Dim requested changes
В задании сказано "Подключение нестандартных шрифтов в формате WOFF2", для чего добавлены ttf?

img/index-background.jpg изображение не должно включать в себя декоративный элемент снизу.

2022-06-26 03:11 UTC, Dima-Dim commented on index.html
>      </div>
Где был открыт этот div?

2022-06-26 03:11 UTC, Dima-Dim commented on styles/styles.css
> +  list-style: none;
Тут ты это делаешь заранее двух классов, далее для некоторых делаешь оп месту. Действуй единнообразно. Лучше делать это по месту.

2022-07-04 06:44 UTC, Dima-Dim commented
Не вижу изменений по вот этим комментариям:
> В задании сказано "Подключение нестандартных шрифтов в формате WOFF2", для чего добавлены ttf?

> img/index-background.jpg изображение не должно включать в себя декоративный элемент снизу.

2022-07-05 05:43 UTC, Dima-Dim commented
> img/index-background.jpg изображение не должно включать в себя декоративный элемент снизу.

2022-07-05 05:46 UTC, Dima-Dim requested changes

2022-07-05 05:46 UTC, Dima-Dim commented on styles/styles.css
> +  background-image: url("../img/index-background.jpg");
Раз уж мы продолжаем разбираться с изображением, за одно. Такой подход не самый лучший, потому что это изображение относится конкретно к промоблоку, а не ко всей странице.

2022-07-05 07:28 UTC, RenEstel commented on styles/styles.css
> +  background-image: url("../img/index-background.jpg");
а как сделать?

2022-07-06 05:53 UTC, Dima-Dim commented on styles/styles.css
> +  background-image: url("../img/index-background.jpg");
Сделать так, чтобы изображение в разметке было в том блоке к которому оно логически относится.

2022-07-06 12:09 UTC, Dima-Dim requested changes

2022-07-06 12:09 UTC, Dima-Dim commented on index.html
> +  <div class="index-background">
https://up.htmlacademy.ru/htmlcss/34/criteries#HTML-06

2022-07-07 06:27 UTC, merged